name = input("enter your name: ")
lastname = input("enter your lastname: ")

print("Your Full Name" ,name , lastname , )
first=int(input("enter your first number: "))
second=int(input("enter your second number: "))
print(first - second)
third=int(input("enter your first number: "))
fourth=int(input("enter your first number: "))
print(third + fourth)
fifth=int(input("enter your second number: "))
print(fourth // fifth)
sixth=int(input("enter your firts number: "))
seventh=int(input("enter your second number: "))
print(sixth * seventh)